from exorde_lab

COPY . /exorde/data
RUN pip3.10 install exorde/data
RUN pip3.10 install /exorde/data/scraping/reddit
RUN pip3.10 install /exorde/data/scraping/twitter
RUN pip3.10 install /exorde/data/scrapping/4chan
RUN pip3.10 install --upgrade git+https://github.com/JustAnotherArchivist/snscrape.git

